export const errorMessage: { [key: string]: string } = {
  E4000: 'Invalid Argument. Not found body in request.',
  E4001: 'Invalid Argument. Body was not valid json format.',
  E4002: 'Invalid Argument. Input paramter validation failed.',
  E4003: 'Invalid Argument. photo must be base64 formatted string and size must be under 1.4MB.',
  E4004: 'Invalid Argument. model_name should be either [1.5, 2.0] as string. current value is ${value}.',
  E4005: 'Invalid Argument. similarity_image_search_ids must be array of string, [0 to 512], string length <= 200.',
  E4006: 'Invalid Argument. similarity_image_search_metas must be array of string, [0 to 512], string length <= 1024.',
  E4007: 'Invalid Argument. similarity_image_search_ids must be number [0 - 65535]. current value is ${value}.',
  E4008: 'Invalid Argument. Size of photo must be less than 2MB. current value is ${value} MB',
  E4009: 'Invalid Argument. photo must be base64 formatted string.',
  E4010: 'Invalid Argument. photo must be jpeg image.',
  E4011: 'Invalid Argument. legacy_flag must be boolean. current value is ${value}.',
  E4012: 'Invalid Argument. similarity_image_search_metas must be base64 formatted string.',
  E4013: 'Invalid Argument. similarity_image_search_metas was input, but similarity_image_search_ids was not input.',
  E4014:
    'Invalid Argument. similarity_image_search_metas was input, but similarity_image_search_threshold was not input.',
  E4015: 'Invalid Argument. similarity_image_search_metas/similarity_image_search_ids array length diffrent',
  E4020: 'Invalid Argument. Not found header',
  E4021: 'Invalid Argument. Not found Content-Type, or Content-Type is not application/json ',
  E4022: 'Invalid Argument. Parameter was not allowed.',
  E4023: 'Invalid Argument. model_name should be 1.5 as string. current value is ${value}.',
  E4099: 'Invalid Argument. Unknown Error',
  E5020: 'Internal server error.',
  E5021: 'Internal server error.',
  E5022: 'Internal server error.',
  E5023: 'Internal server error.',
  E5024: 'Internal server error.',
  E5025: 'Internal server error.',
  E5099: 'Internal server error.',
};
